# Generated by Django 4.2.23 on 2025-07-28 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='category_choice',
            field=models.CharField(choices=[('Super', 'Super'), ('Sports', 'Sports'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hyper', 'Hyper'), ('Hatchback', 'Hatchback'), ('Luxury', 'Luxury'), ('Electric', 'Electric'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='new_or_used',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='New', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='torque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user')),
            ],
        ),
    ]
