# Generated by Django 4.2.23 on 2025-07-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_remove_car_owner_car_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category_choice',
            field=models.CharField(choices=[('Hyper', 'Hyper'), ('Super', 'Super'), ('Sports', 'Sports'), ('Sedan', 'Sedan'), ('Luxury', 'Luxury'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Electric', 'Electric'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
