# Generated by Django 4.2.23 on 2025-07-29 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_car_category_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='category_choice',
        ),
        migrations.RemoveField(
            model_name='car',
            name='horsepower',
        ),
        migrations.RemoveField(
            model_name='car',
            name='torque',
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Hyper', 'Hyper'), ('Super', 'Super'), ('Sports', 'Sports'), ('Sedan', 'Sedan'), ('Luxury', 'Luxury'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Electric', 'Electric'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.car')),
            ],
        ),
    ]
