# Generated by Django 4.2.23 on 2025-07-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_car_category_choice_remove_car_horsepower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(default='defaults/default_car_image.jpg', upload_to='car_images/'),
        ),
    ]
