# Generated by Django 4.2.23 on 2025-07-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_carimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Bugatti', 'Bugatti'), ('Ferrari', 'Ferrari'), ('Ford', 'Ford'), ('Lamborghini', 'Lamborghini'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Porsche', 'Porsche'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='drivetrain',
            field=models.CharField(choices=[('FWD', 'FWD'), ('RWD', 'RDW'), ('AWD', 'AWD'), ('4WD', '4WD'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='Unknown Model', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='torque',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Hyper', 'Hyper'), ('Super', 'Super'), ('Sports', 'Sports'), ('Sedan', 'Sedan'), ('Luxury', 'Luxury'), ('Coupe', 'Coupe'), ('Roadster', 'Roadster'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
