# Generated by Django 4.2.23 on 2025-07-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_car_image_car_brand_car_drivetrain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
    ]
