# Generated by Django 4.2.23 on 2025-07-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Semi-Automatic', 'Semi-Automatic'), ('CVT', 'CVT'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
