# Generated by Django 4.2.23 on 2025-07-29 11:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_car_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='acceleration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='car',
            name='available_colors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Silver', 'Silver'), ('Gray', 'Gray'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Brown', 'Brown'), ('Other', 'Other')], default=['Other'], max_length=71),
        ),
        migrations.AddField(
            model_name='car',
            name='top_sppeed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Silver', 'Silver'), ('Gray', 'Gray'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Brown', 'Brown'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
