# Generated by Django 4.2.23 on 2025-07-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_car_owner_delete_session_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='No comment text'),
        ),
        migrations.AddField(
            model_name='comment',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='web.hashtag'),
        ),
    ]
