# Generated by Django 4.2.23 on 2025-07-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_hashtag_remove_comment_content_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
