# Generated by Django 4.2.23 on 2025-07-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='top_sppeed',
        ),
        migrations.AddField(
            model_name='car',
            name='top_speed',
            field=models.IntegerField(default=0),
        ),
    ]
